server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
